name: Latest blog post workflow
on:
  push:
  schedule: 
  # Run workflow automatically one hour
    - cron: '0 * * * *' 
    
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "WORDPRESS"
          feed_list: "https://hjrdev.wordpress.com/feed/"

      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "DEVTO"
          feed_list: "https://dev.to/feed/jrdev"

      📊 This week I spent my time on


       